### ISSUE TITLE
Get Sleep Timestamps

### ISSUE THREAD

**Issue by jbpauly** [pelo-tech/whoop-api-spec#5]
@DovOps @pelo-tech thanks for this API  together! I can see the detailed sleep information available. Is is possible to get the start and end timestamps of a period of sleep? The way I interpret it and see after testing the Google-Sheet GUI, there's only duration information.

**Comment by DovOps** [comment]
@jbpauly - sure.  I'll add that to the google sheet..  See pelo-tech/whoop-google-sheets#3
Closing this issue out

**Comment by jbpauly** [comment]
Awesome! Thanks @DovOps.
